// literary.js — a large corpus of original, interesting, ASCII-clean prose to type
// (nature, cities, science, history, art, music, food, the ocean, memory, small
// human moments, craft, animals, seasons, the night sky). Bundled so Adaptive and
// the Sentences level have real variety instead of cycling a tiny set.
export const LITERARY = [
  'Moss creeps across the north side of every stone, quietly keeping its own compass.',
  'Lichen spreads in slow gray continents over bark that has forgotten what season it is.',
  'Oaks drop great scatters of acorns in a good year and mean none of it personally.',
  'Ferns unfurl like green question marks, each one asking the same patient question.',
  'Wildflowers do not care that the field was mowed last week; they simply return.',
  'Roots travel farther underground than branches ever reach toward the sky.',
  'Dew collects on spiderwebs each dawn, turning ordinary fences into jeweled ones.',
  'Fallen logs become a hundred small apartments before they become soil again.',
  'Bees remember flowers the way we remember faces, by shape and by scent.',
  'Rivers carve canyons not through force but through the patience of forever.',
  'Prairie grass bends in waves that look like water pretending to be land.',
  'Mushrooms are mostly rumor; the real organism spreads unseen beneath the leaves.',
  'Forest floors in autumn smell like every summer they ever held.',
  'Ice forms first at the edges of a pond, shy and testing the water.',
  'Thistles guard their seeds with spines, then hand them to the wind for free.',
  'Fog does not fall or rise; it simply arrives, already everywhere at once.',
  'Lightning finds the tallest complaint in a landscape and answers it instantly.',
  'Humid afternoons in July can make even shade feel like an argument.',
  'Snow muffles a city until the trucks and shovels start their quiet war.',
  'Thunder always arrives late to its own lightning, apologizing the whole way.',
  'Hail falls like the sky changed its mind about being gentle.',
  'Wind does not blow through a canyon so much as decide to live there.',
  'Rainbows are just light confessing everything it usually keeps to itself.',
  'Frost writes on windows in a handwriting no one has ever learned to read.',
  'Clouds pile up before a storm like an argument nobody wants to have first.',
  'Drought turns a riverbed into a museum of the water that used to be there.',
  'Cold fronts move through like a stranger who rearranges the furniture and leaves.',
  'Heat lightning flickers with no thunder, a rumor with no proof behind it.',
  'Sleet cannot decide between rain and snow, so it insists on being both.',
  'Barometric pressure drops before we feel it, the way dread arrives before bad news.',
  'Lisbon\'s trams climb hills so steep that gravity seems like a suggestion, not a law.',
  'Istanbul sits on two continents and somehow keeps both of them for breakfast.',
  'New Orleans buries its dead above ground, since the water refuses any other plan.',
  'Kyoto hides a thousand small temples behind ordinary doors on ordinary streets.',
  'Chicago\'s alleys carry the real conversation the avenues are too polite to have.',
  'Marrakech smells like cumin and diesel and orange blossoms, often in the same breath.',
  'Reykjavik heats its sidewalks with the same earth that once frightened its settlers.',
  'Venice floods on purpose now, since the tide gauges gave up pretending otherwise.',
  'Mumbai\'s local trains move more people each morning than some countries hold.',
  'Subway maps are a city\'s confession of what it thinks matters most.',
  'Rooftops in Havana hide gardens the street below never suspects exist.',
  'Copenhagen builds its bridges for bicycles first and cars as an afterthought.',
  'Cairo\'s traffic obeys a logic that visitors mistake for chaos and locals call rhythm.',
  'Seoul never quite turns its lights off, as if darkness were bad manners.',
  'Old buildings in most cities are usually the shortest, hiding behind newer ambition.',
  'Packing light is a philosophy disguised as a suitcase decision.',
  'Train windows turn any ordinary field into a story you did not ask for.',
  'Jet lag is just your body arguing about what time it is allowed to believe.',
  'Good souvenirs weigh nothing: a phrase, a smell, a stranger\'s small kindness.',
  'Getting lost on purpose is the only reliable way to find a city\'s real face.',
  'Airports at three in the morning belong to a country that has no flag.',
  'Long bus rides teach patience the way nothing else quite manages to.',
  'Border crossings turn a line on a map into a very real conversation.',
  'Travelers collect stamps in passports the way children once collected stones.',
  'Guidebooks can tell you where to stand, never what you will feel there.',
  'Missing a connection sometimes hands you the trip you actually needed.',
  'Local buses stop wherever someone waves, a schedule made of good faith.',
  'One ferry ride can rearrange your whole sense of what an island means.',
  'Hiking a ridge at dawn makes the whole valley look freshly invented.',
  'Every departure gate is a small rehearsal for the larger business of leaving.',
  'Just a spoonful of neutron star would outweigh every car on this planet combined.',
  'Octopuses taste with their arms, which makes touching and tasting the same gesture.',
  'Light from certain stars left home before humans learned to write anything down.',
  'Gravity is not a force so much as a shape that space agrees to hold.',
  'Your body replaces most of its cells within a decade, quietly, without asking.',
  'Hummingbird hearts can beat astonishingly fast within a single minute.',
  'Glass is technically a liquid that simply forgot how to hurry.',
  'Bacteria outnumber human cells in your body, and mostly they are on your side.',
  'Sound cannot travel through the vacuum of space; out there, nothing shouts.',
  'No two people ever see quite the same rainbow; it is a private event.',
  'Trees communicate through fungal networks some scientists call the wood wide web.',
  'The speed of light is not a limit so much as the universe\'s only fixed rule.',
  'Water expands when it freezes, which is why ice floats instead of sinking.',
  'Venus has the odd fate of a year shorter than one of its own days.',
  'Cells divide, specialize, and forget they were ever identical twins.',
  'Ancient Rome had running water in some homes centuries before most of Europe caught up.',
  'Scribes copying by candlelight once carried the whole memory of a civilization.',
  'The Library of Alexandria burned slowly, in pieces, over centuries, not in one night.',
  'Sailors once navigated entire oceans using only stars, patience, and careful guesswork.',
  'Salt was once so valuable that soldiers were partly paid in it.',
  'One bad harvest could topple a kingdom faster than any invading army.',
  'Handwritten letters carried news across empires at the speed of a horse and a prayer.',
  'Ancient astronomers tracked eclipses centuries before they understood what caused them.',
  'Coins tell more honest history than most monuments, since kings could not resist their faces.',
  'Entire cities were built, abandoned, and forgotten before anyone wrote their names down.',
  'Medieval clocks struck the hour long before they could reliably tell you what hour it was.',
  'Explorers once sailed off maps that simply ended in blank, hopeful ink.',
  'One printing press could out argue a thousand town criers.',
  'Empires rise on roads and fall on debts, more often than they fall on battles.',
  'Old ships carried spices, disease, and rumor in roughly equal measure.',
  'One brushstroke can carry more argument than a paragraph of explanation.',
  'Sculptors claim they only remove what should never have been stone in the first place.',
  'Blank canvases are not empty; they are simply patient.',
  'Perspective was once a trick, before it became a rule everyone assumed was obvious.',
  'Frescoes were painted onto wet plaster, so the artist raced the wall itself to finish.',
  'Forgeries only fail once someone finally asks the right question of them.',
  'Negative space does most of the quiet work in a painting no one credits.',
  'Unfinished sculptures can feel more alive than finished ones.',
  'Color theory is physics that painters agreed to trust before science explained it.',
  'One museum wall can hold four centuries of quiet argument about beauty.',
  'Restorers sometimes discover a whole earlier painting hiding beneath the loved one.',
  'Signatures in the corner of a canvas are often the least interesting thing on it.',
  'Printmaking lets one image live a hundred separate lives from a single carved block.',
  'Some of the most famous paintings were rejected outright by their own painters peers.',
  'Galleries argue quietly with everyone who walks through them, even in silence.',
  'A single sustained note can hold more tension than an entire verse of lyrics.',
  'Silence between notes is not empty; a good musician treats it as an instrument.',
  'Perfect pitch is rare, but almost anyone can learn to hear a wrong one.',
  'Orchestras tune themselves to an oboe because its pitch refuses to wander.',
  'Songs can return a whole decade to you in under four minutes.',
  'Drummers keep time the way a heartbeat does, mostly unnoticed until it stops.',
  'Folk songs survive by being sung wrong just enough to stay alive.',
  'Cracked violins can still hold a better tone than flawless ones.',
  'Whistling is the only instrument every human is born already owning.',
  'Choirs blending perfectly can make forty separate voices sound like one.',
  'Jazz treats a wrong note as an opinion rather than a mistake.',
  'One chord change can turn a happy song quietly sad.',
  'Concert halls are built to bend sound gently, like rooms shaped for listening.',
  'Metronomes cannot feel a song; they can only measure it.',
  'Some instruments take a decade before a player and the wood finally agree on tone.',
  'Bread rises because yeast is quietly, patiently exhaling.',
  'Good stock takes all day and tastes like patience made liquid.',
  'Salt does not make food salty so much as make food sound more like itself.',
  'Bitter greens exist to remind the tongue that sweetness is not the only point.',
  'Market stalls at dawn tell you more about a country than any guidebook.',
  'Fermentation is just controlled decay that we decided to be grateful for.',
  'The best soup in any city is rarely the one with the nicest sign outside.',
  'Sourdough starters get named and inherited like small, needy pets.',
  'Spices traveled farther and changed more history than most wars ever managed.',
  'Recipes passed down without measurements trust memory more than accuracy.',
  'Butter and time can turn almost any vegetable into an argument for patience.',
  'One ripe tomato in August makes every winter tomato look like an apology.',
  'Street food survives because it answers to hungry customers, not to critics.',
  'Cheese is simply milk convinced to become something more opinionated.',
  'Shared meals negotiate more peace than most formal treaties ever manage.',
  'The deep ocean holds more unmapped territory than the entire surface of Mars.',
  'Tides are the moon\'s slow, patient handwriting across every coastline on earth.',
  'Waves crossing the Pacific can travel for days before they finally break.',
  'Coral reefs are animal, mineral, and architecture all arguing to be the same thing.',
  'Bioluminescent plankton turn a night swim into something close to swimming through static.',
  'Whales sing songs that drift for hundreds of miles through water that carries them well.',
  'Salt water heals almost nothing and still convinces most of us that it does.',
  'Tide pools are whole ecosystems pretending to be puddles.',
  'Deep sea creatures glow, flatten, or vanish, since sunlight never reaches that far down.',
  'An anchor holds a ship the way memory holds a person, by faith more than force.',
  'Storms at sea rearrange coastlines faster than most governments can rearrange laws.',
  'A lighthouse exists to promise sailors that someone on land remembers them.',
  'Kelp forests sway underwater with the patience only plants without wind ever learn.',
  'The ocean floor hides mountain ranges taller than anything above the waterline.',
  'Sailors once judged coming weather by watching how the gulls chose to fly.',
  'A childhood kitchen smell can return you to age seven faster than any photograph.',
  'Memory edits quietly, the way a river reshapes its own banks over years.',
  'We remember arguments almost perfectly and kindness only in outline.',
  'A half forgotten song can surface a whole summer you thought you had lost.',
  'Old photographs lie a little, since no one photographs an ordinary Tuesday.',
  'Smell reaches memory faster than any other sense, arriving before we can brace for it.',
  'Some memories improve every year they are retold, like wine that never existed.',
  'We forget most of a year and remember a single afternoon of it in full detail.',
  'Handwriting from childhood looks like a stranger practicing to become you.',
  'A familiar street can rearrange twenty years into a single walk.',
  'Grief and memory share an address; you rarely visit one without the other.',
  'Nostalgia softens the truth the way years soften a stone in a river.',
  'A single object in a drawer can hold an entire decade hostage.',
  'We remember faces longest and names first, in an order that never feels fair.',
  'Dreams borrow real memories and rearrange the furniture without asking permission.',
  'A stranger holding a door a second longer than necessary can change an entire morning.',
  'Someone always laughs first at a joke that no one else quite understood.',
  'A shared umbrella in a sudden downpour turns two strangers into brief allies.',
  'Children negotiate the rules of an invented game with the seriousness of treaty lawyers.',
  'An old couple splitting one dessert with two forks says more than any anniversary card.',
  'A dog waiting at a window each evening keeps better time than most clocks.',
  'Someone humming quietly while they work rarely notices they are doing it.',
  'A handwritten note left on a counter can outlast a hundred forgotten texts.',
  'A crowded elevator briefly agrees on silence, as if by unspoken vote.',
  'A small child insists on carrying the heaviest bag, just to prove something.',
  'Two strangers waiting for the same late bus eventually start talking about the weather.',
  'A grandmother\'s recipe card, stained and worn, is really a small family archive.',
  'Someone always saves the last slice, then quietly hopes no one takes it either.',
  'A neighbor waving from a porch can make an ordinary street feel like a small country.',
  'A child asking why for the fifth time is doing better philosophy than most adults manage.',
  'A woodworker sands with the grain because wood remembers which way it grew.',
  'Good stitching hides most of its effort on the inside of the seam.',
  'A blacksmith listens to the ring of the hammer to know when the metal is ready.',
  'Pottery collapses at the wheel the moment a hand loses its patience.',
  'A well made chair should disappear under the person sitting in it.',
  'Weaving turns two simple directions, over and under, into an entire pattern.',
  'A carpenter measures twice not from doubt but from respect for the wood.',
  'Leatherwork rewards patience and punishes anyone in a hurry to finish.',
  'A tailor reads a body the way a cartographer reads a coastline.',
  'Glassblowing demands a strange kind of trust in something you cannot yet touch.',
  'A good knife holds an edge because someone respected the angle of the stone.',
  'Bookbinding is mostly geometry disguised as an act of quiet devotion.',
  'A potter\'s wheel forgives almost nothing and teaches almost everything.',
  'Hand carved letters read differently than printed ones, though few can say why.',
  'A craftsman\'s tools wear down in a shape that matches exactly how they were held.',
  'Crows recognize individual human faces and apparently hold onto the grudge for years.',
  'Elephants return to the bones of their dead, standing there for reasons no one fully understands.',
  'A cat\'s purr may actually help heal its own bones, which seems almost too convenient.',
  'Migrating birds navigate partly by the earth\'s magnetic field, a compass none of us can feel.',
  'Octopuses solve puzzles, open jars, and seem thoroughly unimpressed by all of it.',
  'Wolves howl less to threaten and more to simply locate each other in the dark.',
  'A horse can read human facial expressions almost as well as another human can.',
  'Beavers reshape entire landscapes, one careful branch and one stubborn dam at a time.',
  'Dolphins call each other by name, using a whistle no two dolphins share.',
  'A tortoise can outlive several generations of the family that first adopted it.',
  'Ants farm fungus underground with more coordination than most human committees manage.',
  'Owls fly almost silently, since their feathers are built to swallow their own sound.',
  'A hedgehog rolling into a ball is really just very polite about its own fear.',
  'Salmon return to the exact stream where they hatched, guided by memory and smell.',
  'A parrot mimicking a voice is choosing which sounds it thinks are worth repeating.',
  'Spring arrives in the small print before it arrives in the weather: buds, not blossoms.',
  'Autumn convinces a whole forest to let go at once, calmly, without argument.',
  'Summer evenings stretch later each week until one day they quietly stop.',
  'Winter teaches patience to anything trying to survive it above ground.',
  'The first frost of the year always arrives like an uninvited but expected guest.',
  'Spring mud is the price paid for everything that will bloom later.',
  'A single warm week can fool an entire orchard into blooming far too soon.',
  'Autumn light turns gold about an hour earlier than summer light ever bothered to.',
  'Winter nights grow long enough that stars start to feel like old neighbors.',
  'Summer thunderstorms clear the air the way an honest argument sometimes clears a room.',
  'The last leaf on a tree always seems to hang on far longer than logic allows.',
  'Spring rain smells different than any other rain, greener somehow, more hopeful.',
  'A single hard frost can end a whole season of tomatoes overnight.',
  'Autumn markets fill with squash in every shape, as if color itself were harvested too.',
  'Winter mornings arrive dark now, and the whole world seems to wake up reluctantly.',
  'A meteor shower is really just the earth passing through the debris of an old comet.',
  'Some stars we see tonight burned out long before telescopes even existed.',
  'The Milky Way is not a phrase for the sky; it is the actual galaxy we live inside.',
  'A new moon is not an absent moon, only one turned fully away from the light.',
  'Constellations are less about the stars themselves than about the shapes we insist on seeing.',
  'Saturn\'s rings are made of ice and rock, no thicker in places than a house.',
  'A clear night far from any city reveals far more stars than most people ever see.',
  'The North Star holds still while every other star seems to circle around it.',
  'Auroras happen when the sun\'s own wind collides with the earth\'s magnetic shield.',
  'A full moon rising looks larger near the horizon, though no one is fully certain why.',
  'Shooting stars are rarely stars at all, just dust burning up on its way down.',
  'Venus is often the brightest thing in the sky besides the sun and the moon.',
  'Ancient sailors steered whole voyages by memorizing which stars rose first each night.',
  'A total eclipse turns midday briefly into a strange and unscheduled twilight.',
  'The universe is still expanding, quietly, in every direction, all the time.',
];
