// words.js — bundled word/sentence corpus + letter-mask filtering.
//
// Imports only the static literary corpus (another leaf). Powers the
// words → sentences fluency phase. A word/sentence is only ever shown if every
// character is a key the learner has already mastered (filtering lives here for
// words; sentences are filtered in engine.js, which knows pool/mastery state).

import { LITERARY } from './literary.js';

// ~2000 common English words, roughly frequency-ordered. All /^[a-z]{1,12}$/ — no
// apostrophes, hyphens, or capitals; no duplicates. ('i' dropped, 'a' kept.)
export const WORDS = [
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it',
  'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this',
  'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or',
  'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so',
  'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me', 'when',
  'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take', 'people',
  'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than',
  'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also', 'back',
  'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way', 'even',
  'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us', 'is',
  'was', 'are', 'been', 'has', 'had', 'were', 'said', 'did', 'made', 'find',
  'here', 'thing', 'many', 'such', 'long', 'high', 'every', 'part', 'place', 'right',
  'great', 'small', 'large', 'next', 'early', 'young', 'few', 'last', 'own', 'under',
  'water', 'never', 'again', 'off', 'away', 'still', 'life', 'world', 'school', 'house',
  'hand', 'eye', 'word', 'name', 'home', 'week', 'side', 'kind', 'head', 'far',
  'once', 'while', 'help', 'talk', 'turn', 'move', 'live', 'show', 'play', 'run',
  'walk', 'open', 'close', 'read', 'write', 'hear', 'grow', 'keep', 'begin', 'seem',
  'feel', 'try', 'ask', 'need', 'call', 'tell', 'become', 'leave', 'put', 'mean',
  'let', 'must', 'child', 'group', 'story', 'fact', 'money', 'month', 'book', 'paper',
  'room', 'friend', 'night', 'point', 'family', 'light', 'idea', 'body', 'car', 'city',
  'game', 'line', 'end', 'food', 'tree', 'song', 'road', 'door', 'fire', 'plan',
  'love', 'hope', 'true', 'best', 'sure', 'able', 'free', 'real', 'full', 'hard',
  'easy', 'late', 'left', 'less', 'more', 'much', 'near', 'pure', 'poor', 'rich',
  'safe', 'same', 'slow', 'soft', 'warm', 'wide', 'wild', 'wise', 'blue', 'cold',
  'dark', 'deep', 'fast', 'fine', 'gold', 'green', 'nice', 'pink', 'red', 'white',
  'add', 'boat', 'bird', 'cat', 'dog', 'egg', 'farm', 'fish', 'hill', 'king',
  'going', 'being', 'doing', 'saying', 'making', 'taking', 'coming', 'looking', 'working', 'getting',
  'having', 'giving', 'finding', 'telling', 'asking', 'trying', 'using', 'seeing', 'feeling', 'knowing',
  'thinking', 'calling', 'keeping', 'letting', 'running', 'moving', 'living', 'playing', 'reading', 'writing',
  'turning', 'walking', 'talking', 'helping', 'showing', 'growing', 'opening', 'closing', 'hearing', 'holding',
  'sitting', 'standing', 'staying', 'starting', 'stopping', 'sending', 'buying', 'paying', 'lasting', 'adding',
  'wanting', 'needing', 'placing', 'passing', 'serving', 'setting', 'meeting', 'leading', 'losing', 'winning',
  'learning', 'teaching', 'building', 'carrying', 'cutting', 'falling', 'filling', 'joining', 'killing', 'listing',
  'marking', 'naming', 'pulling', 'pushing', 'raising', 'saving', 'seeking', 'selling', 'sharing', 'singing',
  'sleeping', 'solving', 'sorting', 'spending', 'testing', 'tracking', 'waiting', 'watching', 'wearing', 'willing',
  'wishing', 'wrapping', 'went', 'gave', 'took', 'came', 'saw', 'knew', 'told', 'felt',
  'kept', 'found', 'brought', 'thought', 'bought', 'caught', 'taught', 'sought', 'fought', 'held',
  'sold', 'sent', 'spent', 'built', 'meant', 'lost', 'won', 'ran', 'sat', 'stood',
  'began', 'broke', 'chose', 'drove', 'fell', 'flew', 'grew', 'heard', 'hid', 'hit',
  'led', 'paid', 'rose', 'sang', 'slept', 'spoke', 'swam', 'threw', 'wore', 'wrote',
  'asked', 'called', 'looked', 'worked', 'played', 'turned', 'walked', 'talked', 'helped', 'showed',
  'opened', 'closed', 'started', 'stopped', 'wanted', 'needed', 'watched', 'waited', 'moved', 'lived',
  'loved', 'liked', 'tried', 'used', 'placed', 'passed', 'served', 'added', 'ended', 'joined',
  'filled', 'pulled', 'pushed', 'raised', 'saved', 'shared', 'tested', 'learned', 'listed', 'marked',
  'named', 'wrapped', 'wished', 'things', 'words', 'names', 'homes', 'weeks', 'sides', 'kinds',
  'heads', 'hands', 'eyes', 'years', 'days', 'times', 'places', 'parts', 'rights', 'groups',
  'stories', 'facts', 'books', 'papers', 'rooms', 'friends', 'nights', 'points', 'families', 'lights',
  'ideas', 'bodies', 'cars', 'cities', 'games', 'lines', 'ends', 'foods', 'trees', 'songs',
  'roads', 'doors', 'fires', 'plans', 'boats', 'birds', 'cats', 'dogs', 'eggs', 'farms',
  'hills', 'kings', 'houses', 'schools', 'worlds', 'lives', 'waters', 'months', 'moneys', 'answer',
  'answers', 'number', 'numbers', 'system', 'program', 'company', 'country', 'problem', 'service', 'result',
  'report', 'market', 'value', 'price', 'order', 'change', 'follow', 'public', 'office', 'health',
  'member', 'person', 'minute', 'letter', 'mother', 'father', 'sister', 'brother', 'parent', 'matter',
  'reason', 'season', 'period', 'figure', 'future', 'common', 'second', 'simple', 'single', 'social',
  'strong', 'better', 'either', 'enough', 'almost', 'always', 'around', 'before', 'behind', 'beyond',
  'during', 'except', 'inside', 'itself', 'myself', 'nearly', 'often', 'rather', 'really', 'seldom',
  'though', 'toward', 'unless', 'within', 'without', 'across', 'against', 'among', 'below', 'beside',
  'between', 'however', 'instead', 'maybe', 'perhaps', 'quite', 'since', 'until', 'whether', 'whole',
  'whose', 'yet', 'above', 'along', 'amount', 'animal', 'appear', 'area', 'arm', 'army',
  'art', 'attack', 'author', 'bank', 'base', 'battle', 'beach', 'bear', 'beat', 'bed',
  'beer', 'belief', 'bell', 'belong', 'bench', 'bill', 'bit', 'bite', 'black', 'blame',
  'blank', 'blood', 'blow', 'board', 'boil', 'bone', 'border', 'bottle', 'bottom', 'bowl',
  'box', 'brain', 'branch', 'brave', 'bread', 'break', 'breath', 'bridge', 'bright', 'bring',
  'broad', 'brown', 'brush', 'budget', 'bug', 'build', 'bunch', 'burn', 'bus', 'bush',
  'busy', 'butter', 'button', 'buy', 'cabin', 'cake', 'camera', 'camp', 'candle', 'cap',
  'capital', 'captain', 'card', 'care', 'career', 'carry', 'case', 'cash', 'cast', 'castle',
  'catch', 'cattle', 'cause', 'ceiling', 'cell', 'center', 'century', 'chain', 'chair', 'chalk',
  'chance', 'charge', 'charm', 'chart', 'cheap', 'check', 'cheese', 'chest', 'chief', 'choice',
  'choose', 'church', 'circle', 'claim', 'class', 'clean', 'clear', 'clerk', 'clever', 'click',
  'client', 'cliff', 'climb', 'clock', 'cloth', 'cloud', 'club', 'coach', 'coal', 'coast',
  'coat', 'code', 'coffee', 'coin', 'collar', 'colony', 'color', 'column', 'combine', 'comfort',
  'command', 'comment', 'compare', 'compete', 'complex', 'concept', 'concern', 'concert', 'confirm', 'connect',
  'consist', 'contact', 'contain', 'content', 'contest', 'context', 'control', 'convert', 'cook', 'cool',
  'copy', 'corn', 'corner', 'cost', 'cotton', 'count', 'county', 'couple', 'course', 'cousin',
  'cover', 'cow', 'crack', 'craft', 'crash', 'cream', 'create', 'credit', 'crew', 'crime',
  'crop', 'cross', 'crowd', 'crown', 'cry', 'cup', 'curious', 'current', 'curtain', 'curve',
  'custom', 'cycle', 'daily', 'damage', 'dance', 'danger', 'data', 'date', 'dead', 'deal',
  'dear', 'debate', 'debt', 'decade', 'decide', 'declare', 'deck', 'decline', 'defeat', 'defend',
  'define', 'degree', 'delay', 'deliver', 'demand', 'dentist', 'deny', 'depend', 'depth', 'desert',
  'design', 'desire', 'desk', 'detail', 'detect', 'develop', 'device', 'devote', 'diet', 'differ',
  'dig', 'dinner', 'direct', 'dirt', 'dirty', 'disease', 'dish', 'dismiss', 'display', 'distant',
  'divide', 'doctor', 'dollar', 'double', 'doubt', 'dozen', 'draft', 'drag', 'drama', 'draw',
  'dream', 'dress', 'drink', 'drive', 'drop', 'drug', 'drum', 'dry', 'duck', 'due',
  'dull', 'dust', 'duty', 'each', 'eager', 'ear', 'earn', 'earth', 'east', 'edge',
  'edit', 'effect', 'effort', 'eight', 'elbow', 'elect', 'element', 'else', 'empty', 'enemy',
  'energy', 'engine', 'enjoy', 'enter', 'entire', 'entry', 'equal', 'error', 'escape', 'essay',
  'estate', 'event', 'ever', 'exact', 'exam', 'example', 'exchange', 'excite', 'excuse', 'exist',
  'exit', 'expand', 'expect', 'expense', 'expert', 'explain', 'explore', 'export', 'express', 'extend',
  'extra', 'extreme', 'fabric', 'face', 'factor', 'fail', 'fair', 'faith', 'false', 'fame',
  'fan', 'fancy', 'farmer', 'fashion', 'fat', 'fate', 'fault', 'favor', 'fear', 'feature',
  'fee', 'feed', 'female', 'fence', 'fever', 'field', 'fifth', 'fifty', 'fight', 'file',
  'film', 'final', 'finger', 'finish', 'firm', 'fit', 'fix', 'flag', 'flame', 'flat',
  'flavor', 'flesh', 'float', 'flood', 'floor', 'flour', 'flow', 'flower', 'fly', 'focus',
  'fold', 'folk', 'force', 'foreign', 'forest', 'forget', 'forgive', 'fork', 'form', 'formal',
  'former', 'fortune', 'forward', 'fourth', 'frame', 'fresh', 'front', 'fruit', 'fuel', 'fun',
  'funny', 'fur', 'gain', 'gap', 'garage', 'garden', 'gas', 'gate', 'gather', 'gear',
  'general', 'gentle', 'gesture', 'ghost', 'giant', 'gift', 'girl', 'glad', 'glass', 'globe',
  'glove', 'glue', 'goal', 'goat', 'god', 'golden', 'golf', 'govern', 'grade', 'grain',
  'grand', 'grant', 'grape', 'grass', 'grave', 'gray', 'grease', 'greet', 'grief', 'grip',
  'ground', 'guard', 'guess', 'guest', 'guide', 'guilt', 'guitar', 'gun', 'habit', 'hair',
  'half', 'hall', 'hammer', 'hang', 'happen', 'happy', 'harbor', 'harm', 'harvest', 'hat',
  'hate', 'heart', 'heat', 'heaven', 'heavy', 'height', 'hello', 'helmet', 'hence', 'herself',
  'hide', 'himself', 'history', 'hobby', 'hold', 'hole', 'holiday', 'hollow', 'holy', 'honest',
  'honey', 'honor', 'hook', 'horn', 'horse', 'host', 'hotel', 'hour', 'huge', 'human',
  'humble', 'humor', 'hundred', 'hungry', 'hunt', 'hurry', 'hurt', 'husband', 'ice', 'ideal',
  'ignore', 'ill', 'image', 'imagine', 'impact', 'import', 'impose', 'improve', 'impulse', 'inch',
  'include', 'income', 'indeed', 'index', 'indoor', 'induce', 'industry', 'infant', 'inform', 'initial',
  'injure', 'injury', 'ink', 'inner', 'input', 'insect', 'insert', 'insist', 'inspect', 'install',
  'instant', 'intend', 'intense', 'invent', 'invest', 'invite', 'involve', 'iron', 'island', 'issue',
  'item', 'jacket', 'jail', 'jam', 'jar', 'jazz', 'jeans', 'jelly', 'jet', 'jewel',
  'job', 'jog', 'join', 'joint', 'joke', 'journey', 'joy', 'judge', 'juice', 'jump',
  'jungle', 'junior', 'jury', 'justice', 'keen', 'kettle', 'key', 'kick', 'kid', 'kill',
  'kiss', 'kitchen', 'knee', 'knife', 'knight', 'knit', 'knock', 'knot', 'label', 'labor',
  'lack', 'ladder', 'lady', 'lake', 'lamp', 'land', 'lane', 'language', 'lap', 'laugh',
  'launch', 'law', 'lawyer', 'lay', 'layer', 'lazy', 'leaf', 'league', 'lean', 'leap',
  'learn', 'lease', 'least', 'leather', 'lecture', 'legal', 'legend', 'lemon', 'lend', 'length',
  'lesson', 'level', 'liberty', 'library', 'license', 'lie', 'lift', 'likely', 'limb', 'limit',
  'link', 'lion', 'lip', 'liquid', 'list', 'listen', 'little', 'load', 'loan', 'lobby',
  'local', 'lock', 'lodge', 'log', 'lonely', 'loop', 'loose', 'lord', 'lorry', 'lot',
  'loud', 'lounge', 'low', 'loyal', 'luck', 'lucky', 'lunch', 'lung', 'luxury', 'machine',
  'mad', 'magic', 'magnet', 'mail', 'main', 'major', 'male', 'mall', 'manage', 'manner',
  'manual', 'map', 'marble', 'march', 'margin', 'marine', 'mark', 'marry', 'mask', 'mass',
  'master', 'match', 'mate', 'math', 'mature', 'maximum', 'mayor', 'meal', 'measure', 'meat',
  'medal', 'media', 'medical', 'medium', 'meet', 'melody', 'melt', 'memory', 'mend', 'mental',
  'mention', 'menu', 'mercy', 'mere', 'merit', 'mess', 'message', 'metal', 'method', 'middle',
  'might', 'mild', 'mile', 'milk', 'mill', 'mind', 'mine', 'mineral', 'minimum', 'minor',
  'miracle', 'mirror', 'miss', 'missile', 'mission', 'mistake', 'mix', 'mixture', 'mobile', 'model',
  'modern', 'modest', 'modify', 'moment', 'monitor', 'monkey', 'mood', 'moon', 'moral', 'morning',
  'mortal', 'motion', 'motive', 'motor', 'mount', 'mouse', 'mouth', 'mud', 'muscle', 'museum',
  'music', 'mutual', 'myth', 'nail', 'narrow', 'nation', 'native', 'nature', 'navy', 'neat',
  'neck', 'needle', 'negative', 'neglect', 'neither', 'nephew', 'nerve', 'nest', 'net', 'network',
  'neutral', 'newly', 'niece', 'nine', 'noble', 'node', 'noise', 'none', 'noon', 'normal',
  'north', 'nose', 'note', 'notice', 'notion', 'novel', 'nowhere', 'nuclear', 'nurse', 'nut',
  'oak', 'obey', 'object', 'oblige', 'observe', 'obtain', 'obvious', 'occasion', 'occupy', 'occur',
  'ocean', 'odd', 'offend', 'offer', 'officer', 'oil', 'old', 'olive', 'omit', 'onion',
  'online', 'onto', 'opera', 'operate', 'opinion', 'oppose', 'option', 'orange', 'orbit', 'orchard',
  'ordeal', 'organ', 'origin', 'ought', 'ounce', 'outcome', 'outdoor', 'outer', 'outline', 'outlook',
  'output', 'outside', 'oven', 'overall', 'overcome', 'owe', 'owl', 'owner', 'oxygen', 'pace',
  'pack', 'package', 'page', 'pain', 'paint', 'pair', 'palace', 'pale', 'palm', 'pan',
  'panel', 'panic', 'pants', 'parade', 'parcel', 'pardon', 'park', 'parking', 'partly', 'partner',
  'party', 'passage', 'passion', 'past', 'pasta', 'pat', 'patch', 'path', 'patient', 'pattern',
  'peak', 'pick', 'pocket', 'quick', 'rank', 'remark', 'risk', 'rock', 'rocket', 'sake',
  'shake', 'shock', 'sick', 'silk', 'queen', 'query', 'quest', 'queue', 'quiet', 'quit',
  'quiz', 'quote', 'square', 'unique', 'equip', 'equity', 'liquor', 'mosque', 'opaque', 'plaque',
  'quack', 'quaint', 'quake', 'qualm', 'quarry', 'quartz', 'quaver', 'quay', 'queasy', 'quell',
  'pave', 'prove', 'remove', 'reveal', 'review', 'revise', 'rival', 'river', 'seven', 'severe',
  'shave', 'silver', 'slave', 'sleeve', 'solve', 'stove', 'survey', 'travel', 'twelve', 'vacant',
  'vague', 'valid', 'valley', 'valve', 'van', 'vanish', 'vary', 'vast', 'vault', 'vendor',
  'venue', 'verb', 'verify', 'verse', 'versus', 'very', 'vessel', 'via', 'vice', 'victim',
  'video', 'view', 'viewer', 'violet', 'violin', 'virtue', 'virus', 'vision', 'visit', 'pillow',
  'powder', 'power', 'raw', 'renew', 'pizza', 'prize', 'puzzle', 'seize', 'size', 'zeal',
  'zebra', 'zero', 'zone', 'zoo', 'breeze', 'bronze', 'cozy', 'crazy', 'dazzle', 'freeze',
  'frenzy', 'frozen', 'gaze', 'graze', 'hazard', 'haze', 'lizard', 'maize', 'nozzle', 'persuade',
  'physical', 'portrait', 'positive', 'possible', 'preserve', 'purchase', 'quantity', 'question', 'research', 'sentence',
  'shoulder', 'terrible', 'thorough', 'together', 'tomorrow', 'transfer', 'ultimate', 'umbrella', 'vertical', 'whenever',
  'wherever', 'apparent', 'appetite', 'approach', 'assemble', 'audience', 'bachelor', 'brilliant', 'champion', 'chocolate',
  'cognitive', 'collapse', 'compound', 'compress', 'conclude', 'concrete', 'condition', 'conflict', 'congress', 'contract',
  'contrast', 'convince', 'courtesy', 'daylight', 'decorate', 'decrease', 'dedicate', 'delicate', 'describe', 'disagree',
  'disaster', 'discount', 'discover', 'distance', 'distinct', 'domestic', 'dominate', 'downtown', 'dreadful', 'economic',
  'effective', 'efficient', 'eligible', 'eliminate', 'emphasis', 'enormous', 'envelope', 'estimate', 'exercise', 'expedite',
  'exposure', 'exterior', 'external', 'farewell', 'festival', 'fidelity', 'flexible', 'forecast', 'foremost', 'fountain',
  'fraction', 'fragment', 'fragrant', 'frequent', 'friction', 'graduate', 'graffiti', 'grateful', 'guarantee', 'guardian',
  'hardship', 'headache', 'headline', 'hemisphere', 'heritage', 'hesitate', 'hierarchy', 'holiness', 'homework', 'horrible',
  'hospital', 'household', 'hurricane', 'ignorant', 'illusion', 'imperial', 'implement', 'improper', 'inability', 'incident',
  'indicate', 'influence', 'initiate', 'injustice', 'innocent', 'innovate', 'instance', 'instinct', 'insulate', 'interact',
  'interest', 'interior', 'internal', 'interval', 'intimate', 'intrigue', 'introduce', 'invasion', 'invisible', 'irrigate',
  'judgment', 'junction', 'juncture', 'kangaroo', 'kindness', 'landmark', 'lifetime', 'lightning', 'likewise', 'limestone',
  'lipstick', 'livestock', 'lollipop', 'lubricate', 'luminous', 'macaroni', 'machinery', 'majority', 'manuscript', 'marathon',
  'marriage', 'mattress', 'meantime', 'meanwhile', 'mechanic', 'medicine', 'meditate', 'membrane', 'memorial', 'metaphor',
  'midnight', 'mischief', 'misplace', 'mistress', 'moderate', 'molecule', 'monastery', 'monetary', 'monument', 'mortgage',
  'multiple', 'mushroom', 'navigate', 'needless', 'negotiate', 'neighbor', 'newcomer', 'newspaper', 'nitrogen', 'nominate',
  'nonsense', 'normally', 'notebook', 'nowadays', 'nuisance', 'numerous', 'nutrient', 'obedient', 'obituary', 'objective',
  'observer', 'obstacle', 'occupant', 'official', 'offspring', 'ointment', 'omission', 'operator', 'opponent', 'opposite',
  'optimism', 'orchestra', 'ordinary', 'organize', 'ornament', 'outbreak', 'outburst', 'overalls', 'overflow', 'overhaul',
  'overhead', 'overhear', 'overload', 'overlook', 'override', 'overrule', 'overseas', 'overtake', 'overtime', 'overturn',
  'pamphlet', 'parachute', 'paradise', 'paragraph', 'parallel', 'paralyze', 'parasite', 'parchment', 'particle', 'password',
  'paternal', 'pavement', 'pavilion', 'peaceful', 'peculiar', 'pedestal', 'penalize', 'penetrate', 'peninsula', 'perceive',
  'perennial', 'perimeter', 'permanent', 'perpetual', 'personal', 'personnel', 'pessimist', 'pesticide', 'petition', 'pharmacy',
  'pheasant', 'phenomena', 'philosophy', 'phonetic', 'phosphate', 'photograph', 'physician', 'pinnacle', 'pipeline', 'pause',
  'pay', 'payment', 'peace', 'peanut', 'pear', 'peasant', 'pen', 'penalty', 'pencil', 'penny',
  'pension', 'pepper', 'per', 'percent', 'perfect', 'perform', 'peril', 'permit', 'persist', 'pet',
  'phase', 'phone', 'photo', 'phrase', 'piano', 'picture', 'pie', 'piece', 'pig', 'pile',
  'pilot', 'pin', 'pine', 'pint', 'pipe', 'pitch', 'pity', 'plain', 'plane', 'planet',
  'plant', 'plastic', 'plate', 'please', 'pleased', 'pledge', 'plenty', 'plot', 'plug', 'plus',
  'poem', 'poet', 'poetry', 'poison', 'pole', 'police', 'policy', 'polish', 'polite', 'pond',
  'pool', 'pop', 'popular', 'port', 'portion', 'pose', 'possess', 'post', 'pot', 'potato',
  'pound', 'pour', 'poverty', 'praise', 'pray', 'prayer', 'precise', 'predict', 'prefer', 'premium',
  'prepare', 'present', 'press', 'pretend', 'pretty', 'prevent', 'pride', 'priest', 'primary', 'prime',
  'prince', 'print', 'prior', 'prison', 'private', 'proceed', 'process', 'produce', 'product', 'profile',
  'profit', 'project', 'promise', 'promote', 'proof', 'proper', 'propose', 'protect', 'protest', 'proud',
  'provide', 'publish', 'pull', 'pulse', 'pump', 'punch', 'punish', 'pupil', 'purple', 'purpose',
  'purse', 'pursue', 'push', 'quality', 'quarter', 'quickly', 'quietly', 'rabbit', 'race', 'racial',
  'radar', 'radio', 'rail', 'rain', 'raise', 'rally', 'ranch', 'random', 'range', 'rapid',
  'rare', 'rat', 'rate', 'ratio', 'ray', 'reach', 'react', 'ready', 'realize', 'rear',
  'rebel', 'recall', 'receipt', 'receive', 'recent', 'recipe', 'record', 'recover', 'recruit', 'reduce',
  'refer', 'reflect', 'reform', 'refuse', 'regard', 'regime', 'region', 'regret', 'regular', 'reject',
  'relate', 'relax', 'release', 'relief', 'rely', 'remain', 'remedy', 'remind', 'remote', 'render',
  'rent', 'repair', 'repeat', 'replace', 'reply', 'request', 'require', 'rescue', 'reserve', 'resist',
  'resolve', 'resort', 'respect', 'respond', 'rest', 'restore', 'retain', 'retire', 'retreat', 'return',
  'revenue', 'reverse', 'reward', 'rhythm', 'ribbon', 'rice', 'ride', 'ridge', 'rifle', 'rise',
];

// ~48 everyday sentences. The first 36 use ONLY letters, capitals, space, comma,
// and period, so they are all eligible the moment sentences unlock. The last dozen
// may additionally use apostrophes, ! or ? (eligible after those keys unlock).
export const SENTENCES = [
  'The quick brown fox jumps over the lazy dog.',
  'She said the meeting starts at noon today.',
  'We walked along the river until the sun went down.',
  'My brother reads a book every single night.',
  'The old house on the hill has a red door.',
  'They planted trees near the school last spring.',
  'A gentle rain fell over the quiet town.',
  'He kept the light on while he wrote his story.',
  'Our team worked hard and finished the plan early.',
  'The children played games in the open field.',
  'I hope you find the time to visit us soon.',
  'Water flows down the long river to the sea.',
  'The teacher asked the class to open their books.',
  'A small bird sang in the tall green tree.',
  'We had a great time at the party last week.',
  'She kept her word and helped us move the boxes.',
  'The city lights looked bright from the high hill.',
  'He learned to play the song in just one day.',
  'They live in a warm house near the blue lake.',
  'The dog ran across the yard to greet the boy.',
  'Please turn off the light before you leave.',
  'My family likes to walk in the park on weekends.',
  'The fast train left the station right on time.',
  'We read the same book and talked about it for hours.',
  'A good friend will always tell you the truth.',
  'The bright moon rose above the dark hills.',
  'She wrote her name at the top of the page.',
  'The farm has cows, sheep, and a small red barn.',
  'He put the keys on the table by the door.',
  'They watched the boats sail out past the shore.',
  'The soft wind moved the leaves across the road.',
  'We made a fire and told stories late into the night.',
  'The young girl drew a picture of her home.',
  'A wise leader listens more than she speaks.',
  'The store closes early on the last day of the week.',
  'He fixed the old clock and set it to the right time.',
  'What time does the next train leave the city?',
  'Can you help me carry these books upstairs?',
  'That was the best meal we have had all year!',
  'Where did you put the map of the old town?',
  'The band played on, and the whole crowd cheered!',
  'Do you know the way to the river from here?',
  'It is a bright, clear morning for a long walk.',
  'She smiled and said, that is a wonderful idea!',
  'How many people are coming to the party tonight?',
  'The waves crashed hard against the rocks below.',
  'We finally reached the top, and the view was amazing!',
  'Why do the best days always seem to pass so fast?',
].concat(LITERARY);   // + ~240 interesting literary passages (variety, so adaptive stops cycling)

// --- letter-mask filtering ----------------------------------------------------
// 'a' -> bit 0 ... 'z' -> bit 25. A word is eligible for a set of allowed letters
// iff every letter bit is within the allowed mask: (wordMask & ~allowed) === 0.

export function maskFor(letters) {
  let m = 0;
  for (const ch of letters) {
    const c = ch.charCodeAt(0) - 97;
    if (c >= 0 && c < 26) m |= (1 << c);
  }
  return m;
}

export function wordMask(word) { return maskFor(word); }

let _masks = null;                 // Int32Array parallel to WORDS, built lazily
const _eligibleCache = new Map();  // allowedMask -> eligible word array (freq order)

function ensureMasks() {
  if (_masks) return;
  _masks = new Int32Array(WORDS.length);
  for (let i = 0; i < WORDS.length; i++) _masks[i] = maskFor(WORDS[i]);
}

// allowed: a bitmask, or any iterable of 'a'..'z'. Returns eligible words in the
// original (frequency) order. Memoized — the mastered-letter set changes rarely.
export function eligibleWords(allowed) {
  const mask = (typeof allowed === 'number') ? allowed : maskFor(allowed);
  if (_eligibleCache.has(mask)) return _eligibleCache.get(mask);
  ensureMasks();
  const out = [];
  for (let i = 0; i < WORDS.length; i++) {
    if ((_masks[i] & ~mask) === 0) out.push(WORDS[i]);
  }
  _eligibleCache.set(mask, out);
  return out;
}
